# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

r_packages:
  - covr
  - data.table
  - pryr
  - stringr
  
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'